# Generated by Django 5.0.4 on 2024-04-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
