# Generated by Django 5.0.4 on 2024-04-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_pokemon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='description',
        ),
        migrations.AddField(
            model_name='boss',
            name='attack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='boss',
            name='defense',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='boss',
            name='pokemon_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='boss',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
