# Generated by Django 5.0.4 on 2024-04-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_remove_game_boss_game_bosses'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.BooleanField(default=True),
        ),
    ]
