# Generated by Django 5.0.4 on 2024-04-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='modifier',
        ),
    ]
