# Generated by Django 5.0.4 on 2024-04-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_remove_gamestats_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='game_stats', to='game_app.modifier'),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='pokemons',
            field=models.ManyToManyField(blank=True, related_name='game_stats', to='game_app.pokemon'),
        ),
    ]
