# Generated by Django 5.0.4 on 2024-04-16 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0007_gamestats_modifiers_gamestats_pokemons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestats',
            name='game',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='game_app.game'),
        ),
    ]
