# Generated by Django 5.0.4 on 2024-04-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0009_alter_gamestats_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestats',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_app.game'),
        ),
    ]
